# Generated by Django 5.1 on 2024-08-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('DW','DRESS WATCHES'),('SM','SMART WATCHES'),('SW','SPORT WATCHES'), ('AW','AUTOMATIC WATCHES'),('CW','CHRONOGRAPH WATCHES'),('DV','DIVING WATCHES')], max_length=20)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
