# Generated by Django 5.1 on 2024-08-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DW','DRESS WATCHES'),('SM','SMART WATCHES'),('SW','SPORT WATCHES'), ('AW','AUTOMATIC WATCHES'),('CW','CHRONOGRAPH WATCHES'),('DV','DIVING WATCHES')], max_length=20),
        ),
    ]
